const {chromium,expect}=require(process.env.PLAYWRIGHT_TEST_MODULE||'playwright/test');
const fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http'),{gzipSync}=require('node:zlib');
const base=path.resolve(process.env.QA_ROOT||'artifacts/Quiz-Pal-HTML'),out=path.resolve(process.env.QA_OUTPUT||'artifacts/qa-release');
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.webp':'image/webp','.ttf':'font/ttf','.woff2':'font/woff2'};
async function startServer(){const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(!u.pathname.startsWith('/contest-preview/'))throw Error();const file=path.resolve(base,decodeURIComponent(u.pathname.slice(17))||'index.html');if(!file.startsWith(base+path.sep))throw Error();let bytes=await fs.readFile(file);const headers={'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'};if(/\.(html|js|css|svg)$/.test(file)&&req.headers['accept-encoding']?.includes('gzip')){bytes=gzipSync(bytes);headers['Content-Encoding']='gzip';}headers['Content-Length']=bytes.length;res.writeHead(200,headers);res.end(bytes)}catch{res.writeHead(404);res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));return {server,url:`http://127.0.0.1:${server.address().port}/contest-preview/`};}
function observers(){window.qaPerf={lcp:[],shifts:[],longTasks:[],events:[]};for(const [type,key]of [['largest-contentful-paint','lcp'],['layout-shift','shifts'],['longtask','longTasks'],['event','events']])try{new PerformanceObserver(list=>{for(const e of list.getEntries())window.qaPerf[key].push({...e.toJSON(),element:e.element?.outerHTML?.slice(0,200),sources:e.sources?.map(s=>({html:s.node?.outerHTML?.slice(0,150),previous:s.previousRect,current:s.currentRect}))})}).observe({type,buffered:true,durationThreshold:16})}catch{}}
async function main(){await fs.mkdir(out,{recursive:true});const {server,url}=await startServer();const browser=await chromium.launch({executablePath:process.env.QA_CHROME||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const report={browser:browser.version(),root:base,results:[],errors:[]};
try{
if(!process.env.QA_LAYOUT_ONLY)for(const mobile of [false,true])for(let run=0;run<3;run++){
const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:900},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:1});const page=await context.newPage();const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});if(mobile){await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:200000,uploadThroughput:93750});}await page.addInitScript(observers);page.on('pageerror',e=>report.errors.push(String(e)));await page.goto(url,{waitUntil:'domcontentloaded',timeout:90000});await expect(page.locator('.product-intro[open]')).toBeVisible({timeout:90000});await page.waitForTimeout(1400);const loaded=await page.evaluate(()=>({ready:performance.now(),navigation:performance.getEntriesByType('navigation').map(e=>e.toJSON()),paint:performance.getEntriesByType('paint').map(e=>e.toJSON()),...qaPerf,resources:performance.getEntriesByType('resource').map(e=>({name:new URL(e.name).pathname,size:e.encodedBodySize,decoded:e.decodedBodySize,duration:e.duration}))}));await page.locator('#productIntroDoNotShow').check();await page.locator('.product-intro-close').click();if(await page.locator('.quiz-tour-skip').isVisible())await page.locator('.quiz-tour-skip').click();const interactions=[];for(let i=0;i<5;i++){const start=performance.now();await page.locator('#nextButton').click();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));interactions.push(performance.now()-start);}loaded.interactionsMs=interactions;loaded.events=await page.evaluate(()=>qaPerf.events);loaded.mobile=mobile;loaded.run=run;report.results.push(loaded);console.log('PERF',JSON.stringify({mobile,run,ready:loaded.ready,lcp:loaded.lcp.at(-1)?.startTime,bytes:loaded.resources.reduce((n,r)=>n+r.size,0),longTasks:loaded.longTasks.length,interactions}));await context.close();}
const context=await browser.newContext();const page=await context.newPage();await page.goto(url);await page.locator('#productIntroDoNotShow').check();await page.locator('.product-intro-close').click();if(await page.locator('.quiz-tour-skip').isVisible())await page.locator('.quiz-tour-skip').click();report.layout=[];
for(const width of [1920,1440,1280,1180,1024,981,980,800,768,721,720,640,390,360,320]){await page.setViewportSize({width,height:900});await page.waitForTimeout(180);if(process.env.QA_CSS)await page.addStyleTag({path:process.env.QA_CSS});const data=await page.evaluate(()=>{const rect=el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return {sel:el.tagName+'.'+el.className,id:el.id,x:r.x,y:r.y,width:r.width,height:r.height,scroll:el.scrollWidth,client:el.clientWidth,display:s.display,grid:s.gridTemplateColumns,minWidth:s.minWidth,overflow:s.overflow,flex:s.flex}};return {width:innerWidth,body:document.documentElement.scrollWidth,main:[...document.querySelectorAll('.app-shell,.sidebar,.main,.topbar,.toolbar,.status-band,.playfield')].map(rect),outside:[...document.querySelectorAll('body *')].filter(el=>{const r=el.getBoundingClientRect();return r.width&&r.right>innerWidth+1&&getComputedStyle(el).position!=='fixed'}).slice(0,25).map(rect),buttons:[...document.querySelectorAll('.toolbar button')].map(el=>{const r=el.getBoundingClientRect();const hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {id:el.id,reachable:!!hit&&(el===hit||el.contains(hit)),x:r.x,y:r.y,width:r.width}})}});report.layout.push(data);await page.screenshot({path:path.join(out,`layout-${width}.png`)});console.log('LAYOUT',width,data.body,data.buttons.filter(x=>!x.reachable).map(x=>x.id));}
report.courses=await page.locator('[data-course]').evaluateAll(es=>es.map(el=>({tag:el.tagName,id:el.dataset.course,text:el.textContent.slice(0,100)})));await context.close();
}finally{await fs.writeFile(path.join(out,'audit.json'),JSON.stringify(report,null,2));await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}}
module.exports={startServer,observers};if(require.main===module)main().catch(e=>{console.error(e);process.exitCode=1});
