"""Preserve all Kaisei glyphs; split common UI characters for on-demand WOFF2 loading."""
from pathlib import Path
import json, argparse
from fontTools.ttLib import TTFont
from fontTools import subset

parser=argparse.ArgumentParser()
parser.add_argument('--output', type=Path, required=True, help='Temporary output directory; inspect before copying into public/')
args=parser.parse_args()
root=Path(__file__).resolve().parents[1]
out=args.output.resolve(); out.mkdir(parents=True, exist_ok=True)
# General UI and bundled questions are common; imported uncommon glyphs remain available.
text=''.join((root/p).read_text(encoding='utf-8') for p in ['index.html','public/product-intro.js','public/data.js'])
text+=(root/'tools/font-common-ui.txt').read_text(encoding='utf-8')
common={ord(c) for c in text}|set(range(0x20,0x100))
def unicode_ranges(values):
    runs=[]
    for n in sorted(values):
        if runs and n==runs[-1][1]+1: runs[-1][1]=n
        else: runs.append([n,n])
    return ','.join('U+%X'%a if a==b else 'U+%X-%X'%(a,b) for a,b in runs)
css=[]; report=[]
for name,weight in [('Regular',400),('Medium',500),('Bold',700)]:
    source=root/f'public/assets/fonts/KaiseiOpti-{name}.ttf'
    original=TTFont(source); cmap=original.getBestCmap(); all_chars=set(cmap)
    groups={'extended':all_chars-common,'common':all_chars&common}
    restored=set()
    for group,chars in groups.items():
        font=TTFont(source); options=subset.Options(); options.layout_features=['*']; options.name_IDs=['*']; options.name_legacy=True; options.name_languages=['*']; options.recalc_timestamp=False
        sub=subset.Subsetter(options=options); sub.populate(unicodes=chars); sub.subset(font); font.flavor='woff2'
        file=out/f'KaiseiOpti-{name}-{group}.woff2'; font.save(file)
        actual=TTFont(file).getBestCmap(); assert chars <= set(actual) <= all_chars
        restored|=set(actual)
        css.append('@font-face {\n  font-family: "Kaisei Opti";\n  src: url("./assets/fonts/%s") format("woff2");\n  font-style: normal;\n  font-weight: %d;\n  font-display: swap;\n  unicode-range: %s;\n}\n'%(file.name,weight,'U+0-10FFFF' if group=='extended' else unicode_ranges(chars)))
        report.append({'file':file.name,'characters':len(chars),'bytes':file.stat().st_size})
    assert restored==all_chars
    print(name, 'all',len(all_chars),'common',len(groups['common']),flush=True)
(out/'fonts.css').write_text('/* Same licensed font outlines, split by Unicode coverage. Generated by build-web-fonts.py. */\n'+''.join(css),encoding='utf-8')
(out/'font-verification.json').write_text(json.dumps({'allOriginalCharactersPreserved':True,'files':report},indent=2),encoding='utf-8')
