import { useEffect, useRef, useState } from "native-ui";
import type { LibrarySnapshot } from "../../domain/types";
import { applyCsvPreview, csvTemplate, issuesCsv, parseCsvFile, type CsvPreview, type DuplicatePolicy } from "../csv-import/csv";
import { downloadBackup, downloadText, parseBackup, restoreBackup, type BackupPayload } from "./backup";

export function DataDialog({ open, onClose, snapshot, reload, announce }: { open: boolean; onClose: () => void; snapshot: LibrarySnapshot; reload: () => Promise<void>; announce: (message: string) => void }) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const [tab, setTab] = useState<"csv" | "backup">("csv");
  const [preview, setPreview] = useState<CsvPreview | null>(null);
  const [policy, setPolicy] = useState<DuplicatePolicy>("skip");
  const [validOnly, setValidOnly] = useState(false);
  const [backup, setBackup] = useState<BackupPayload | null>(null);
  const [csvFileName, setCsvFileName] = useState("");
  const [backupFileName, setBackupFileName] = useState("");
  const [message, setMessage] = useState("");
  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;
    if (open && !dialog.open) dialog.showModal();
    if (!open && dialog.open) dialog.close();
  }, [open]);
  const loadCsv = async (file?: File) => { if (!file) return; setCsvFileName(file.name); setMessage("解析中…"); try { setPreview(await parseCsvFile(file, snapshot)); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "CSVを解析できませんでした。"); } };
  const apply = async () => { if (!preview) return; try { await applyCsvPreview(preview, policy, validOnly); await reload(); announce("CSVを取り込みました。"); setPreview(null); onClose(); } catch (error) { setMessage(error instanceof Error ? error.message : "取り込みに失敗しました。"); } };
  const loadBackup = async (file?: File) => { if (!file) return; setBackupFileName(file.name); setMessage("検証中…"); try { setBackup(await parseBackup(await file.text())); setMessage(""); } catch (error) { setBackup(null); setMessage(error instanceof Error ? error.message : "バックアップを検証できませんでした。"); } };
  const restore = async (mode: "replace" | "merge") => { if (!backup) return; if (mode === "replace" && !confirm("現在の教材と履歴をすべて置き換えます。事前にバックアップしましたか？")) return; await restoreBackup(backup, mode); await reload(); announce("バックアップを復元しました。"); onClose(); };
  return <dialog ref={dialogRef} className="data-dialog" onClose={onClose} aria-labelledby="data-dialog-title">
    <header className="dialog-header data-dialog-header"><div className="data-dialog-title"><span className="data-dialog-mark" aria-hidden="true">D</span><div><span className="eyebrow">DATA DESK</span><h2 id="data-dialog-title">データ管理</h2><p>教材データを安全に取り込み、持ち運べます。</p></div></div><button type="button" className="close-button" onClick={onClose} aria-label="閉じる">×</button></header>
    <div className="tab-list data-tabs" role="tablist"><button type="button" role="tab" aria-selected={tab === "csv"} onClick={() => setTab("csv")}><span>01</span><span><strong>CSV取込</strong><small>表データから教材を追加</small></span></button><button type="button" role="tab" aria-selected={tab === "backup"} onClick={() => setTab("backup")}><span>02</span><span><strong>バックアップ</strong><small>全データを書き出し・復元</small></span></button></div>
    {tab === "csv" ? <div className="dialog-body csv-workspace">
      <section className="csv-upload-card"><div className="data-panel-heading"><span className="data-panel-icon" aria-hidden="true">CSV</span><div><small>IMPORT LIBRARY</small><h3>CSVファイルを検証</h3><p>ファイルを選ぶと、保存前に変更内容と行ごとのエラーを確認できます。</p></div></div><label className="data-file-picker"><input type="file" accept=".csv,text/csv" onChange={(e) => loadCsv(e.target.files?.[0])} /><span className="data-file-symbol" aria-hidden="true">＋</span><span><strong>{csvFileName || "CSVファイルを選択"}</strong><small>{csvFileName ? "選択済み。解析結果を下で確認してください。" : "最大5MB・5,000行 / CSV形式"}</small></span><span className="data-file-action">参照する</span></label><div className="csv-safety-row"><span>数式インジェクション検知</span><span>型・必須項目を検証</span><span>確定前プレビュー</span></div><button type="button" className="text-button data-template-button" onClick={() => downloadText(csvTemplate(), "local-quiz-studio-template.csv", "text/csv;charset=utf-8")}>CSVテンプレートを取得</button></section>
      {preview && <><div className="preview-stats"><span><b>{preview.counts.new}</b> 新規</span><span><b>{preview.counts.duplicate}</b> 重複</span><span className="warning"><b>{preview.counts.warnings}</b> 警告</span><span className="error"><b>{preview.counts.errors}</b> エラー</span></div>
        <label>重複時の扱い<select value={policy} onChange={(e) => setPolicy(e.target.value as DuplicatePolicy)}><option value="skip">重複をスキップ</option><option value="update">既存を更新</option><option value="copy">別データとして追加</option><option value="abort">重複があれば中止</option></select></label>
        {preview.counts.errors > 0 && <label className="check-label"><input type="checkbox" checked={validOnly} onChange={(e) => setValidOnly(e.target.checked)} />正常な行だけ取り込む</label>}
        <h3>変更プレビュー</h3>
        <div className="issue-table" role="region" aria-label="変更プレビュー" tabIndex={0}><table><thead><tr><th>行</th><th>対象</th><th>処理</th><th>内容</th></tr></thead><tbody>{preview.actions.slice(0, 100).map((action, index) => <tr key={`${action.row}-${action.entity.id}-${index}`}><td>{action.row}</td><td>{action.entityType === "subject" ? "科目" : action.entityType === "section" ? "セクション" : "問題"}</td><td>{action.kind === "new" ? "新規" : "重複"}</td><td>{"name" in action.entity ? action.entity.name : action.entity.promptMarkdown}</td></tr>)}</tbody></table></div>
        <h3>検証結果</h3>
        <div className="issue-table" role="region" aria-label="検証結果" tabIndex={0}>{preview.issues.length ? <table><thead><tr><th>行</th><th>列</th><th>種別</th><th>内容</th></tr></thead><tbody>{preview.issues.slice(0, 100).map((issue, index) => <tr key={`${issue.row}-${issue.field}-${index}`}><td>{issue.row}</td><td>{issue.field}</td><td>{issue.severity === "error" ? "エラー" : "警告"}</td><td>{issue.message}</td></tr>)}</tbody></table> : <p className="success-message">検証エラーはありません。</p>}</div>
        <div className="dialog-actions">{preview.issues.length > 0 && <button type="button" className="secondary-button" onClick={() => downloadText(issuesCsv(preview.issues), "csv-errors.csv", "text/csv;charset=utf-8")}>エラーCSV</button>}<button type="button" className="primary-button" onClick={apply} disabled={Boolean(preview.counts.errors && !validOnly)}>取込を確定</button></div></>}
    </div> : <div className="dialog-body backup-workspace"><div className="data-overview"><div><small>COMPLETE DATA PORTABILITY</small><strong>全データを、ひとつのファイルで。</strong></div><div className="data-overview-stats" aria-label="現在の教材データ"><span><b>{snapshot.subjects.length}</b>科目</span><span><b>{snapshot.sections.length}</b>セクション</span><span><b>{snapshot.questions.length}</b>問題</span><span><b>{snapshot.attempts.length}</b>学習記録</span></div></div><div className="backup-grid"><section className="backup-panel export-panel"><div className="data-panel-heading"><span className="data-panel-icon" aria-hidden="true">↓</span><div><small>EXPORT</small><h3>書き出す</h3><p>現在の教材と学習状況を、この端末の外へ保存します。</p></div></div><div className="backup-includes"><span>教材構成</span><span>問題データ</span><span>学習履歴</span><span>画面設定</span></div><div className="data-security-note"><strong>改ざん検知付き</strong><p>チェックサムを付けたJSONとして保存します。APIキーは含みません。</p></div><button type="button" className="primary-button backup-primary-action" onClick={() => void downloadBackup()}><span aria-hidden="true">↓</span><span><strong>完全バックアップを保存</strong><small>JSONファイルをダウンロード</small></span></button></section><section className="backup-panel restore-panel"><div className="data-panel-heading"><span className="data-panel-icon" aria-hidden="true">↑</span><div><small>RESTORE</small><h3>復元する</h3><p>バックアップを検証してから、復元方法を選べます。</p></div></div><label className="data-file-picker restore-file-picker"><input type="file" accept=".json,application/json" onChange={(e) => loadBackup(e.target.files?.[0])} /><span className="data-file-symbol" aria-hidden="true">＋</span><span><strong>{backupFileName || "バックアップJSONを選択"}</strong><small>{backupFileName ? "ファイルを検証しました。" : "ここを押してファイルを選んでください"}</small></span><span className="data-file-action">参照する</span></label>{backup ? <div className="backup-preview"><div className="backup-preview-status"><span aria-hidden="true">✓</span><div><small>検証済み</small><strong>{backup.subjects.length}科目・{backup.sections.length}セクション・{backup.questions.length}問</strong><p>{new Date(backup.exportedAt).toLocaleString("ja-JP")} に作成</p></div></div><div className="restore-mode-copy"><strong>復元方法を選択</strong><p>マージは現在のデータを残します。すべて置換は現在の教材と履歴を上書きします。</p></div><div className="dialog-actions restore-actions"><button type="button" className="secondary-button" onClick={() => restore("merge")}>現在のデータへマージ</button><button type="button" className="danger-button" onClick={() => restore("replace")}>すべて置換</button></div></div> : <div className="restore-waiting"><span aria-hidden="true">✓</span><strong>選択後に内容を検証します</strong><p>科目・セクション・問題数と作成日時を確認してから復元できます。</p></div>}</section></div></div>}
    {message && <p className="form-error data-dialog-message" role="alert">{message}</p>}
  </dialog>;
}
